/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package Views;

/**
 *
 * @author Pipitchu
 */
public class TelaSalaDeEstar extends javax.swing.JFrame {

    /**
     * Creates new form TelaSalaDeEstar
     */
    public TelaSalaDeEstar() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        Sofa1 = new javax.swing.JLabel();
        Sofa4 = new javax.swing.JLabel();
        btComprarSofa1 = new javax.swing.JButton();
        btComprarSofa4 = new javax.swing.JButton();
        jLabel1 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        setTitle("Sala de estar");
        setResizable(false);
        getContentPane().setLayout(null);

        Sofa1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagens/Sofa1.png"))); // NOI18N
        Sofa1.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0), 2));
        getContentPane().add(Sofa1);
        Sofa1.setBounds(100, 40, 304, 229);

        Sofa4.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagens/Sofa4.png"))); // NOI18N
        Sofa4.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0), 2));
        getContentPane().add(Sofa4);
        Sofa4.setBounds(460, 40, 304, 230);

        btComprarSofa1.setText("COMPRAR");
        getContentPane().add(btComprarSofa1);
        btComprarSofa1.setBounds(460, 310, 308, 50);

        btComprarSofa4.setText("COMPRAR");
        getContentPane().add(btComprarSofa4);
        btComprarSofa4.setBounds(100, 310, 304, 50);

        jLabel1.setText("ONDE FICA O PREÇO / QNT");
        getContentPane().add(jLabel1);
        jLabel1.setBounds(100, 270, 304, 40);

        getAccessibleContext().setAccessibleDescription("Sala de estar");

        setSize(new java.awt.Dimension(866, 639));
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(TelaSalaDeEstar.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(TelaSalaDeEstar.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(TelaSalaDeEstar.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(TelaSalaDeEstar.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new TelaSalaDeEstar().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel Sofa1;
    private javax.swing.JLabel Sofa4;
    private javax.swing.JButton btComprarSofa1;
    private javax.swing.JButton btComprarSofa4;
    private javax.swing.JLabel jLabel1;
    // End of variables declaration//GEN-END:variables
}
