/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package Views;

/**
 *
 * @author Pipitchu
 */
public class TelaCadastro extends javax.swing.JFrame {

    /**
     * Creates new form TelaCadastro
     */
    public TelaCadastro() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        txtNome = new javax.swing.JTextField();
        txtCPF = new javax.swing.JTextField();
        txtLogin = new javax.swing.JTextField();
        txtSenha = new javax.swing.JPasswordField();
        txtEstado = new javax.swing.JTextField();
        txtCidade = new javax.swing.JTextField();
        txtRua = new javax.swing.JTextField();
        txtNumero = new javax.swing.JTextField();
        txtComplemento = new javax.swing.JTextField();
        txtTelResidencial = new javax.swing.JTextField();
        txtTelCel = new javax.swing.JTextField();
        btCadastrar = new javax.swing.JButton();
        btLimparDados = new javax.swing.JButton();
        btCancelar = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        setTitle("Cadastrar");
        setResizable(false);
        getContentPane().setLayout(null);

        txtNome.setText("NOME COMPLETO (DPS APAGO O TXT)");
        getContentPane().add(txtNome);
        txtNome.setBounds(50, 50, 230, 30);

        txtCPF.setText("CPF");
        getContentPane().add(txtCPF);
        txtCPF.setBounds(290, 50, 230, 30);

        txtLogin.setText("LOGIN");
        getContentPane().add(txtLogin);
        txtLogin.setBounds(50, 90, 230, 30);

        txtSenha.setText("SENHA");
        getContentPane().add(txtSenha);
        txtSenha.setBounds(290, 90, 230, 30);

        txtEstado.setText("Estado");
        getContentPane().add(txtEstado);
        txtEstado.setBounds(50, 170, 230, 30);

        txtCidade.setText("Cidade");
        getContentPane().add(txtCidade);
        txtCidade.setBounds(290, 170, 230, 30);

        txtRua.setText("Rua");
        getContentPane().add(txtRua);
        txtRua.setBounds(50, 130, 230, 30);

        txtNumero.setText("N°");
        getContentPane().add(txtNumero);
        txtNumero.setBounds(290, 130, 40, 30);

        txtComplemento.setText("Complemento ");
        getContentPane().add(txtComplemento);
        txtComplemento.setBounds(340, 130, 180, 30);

        txtTelResidencial.setText("Telefone Residencial");
        getContentPane().add(txtTelResidencial);
        txtTelResidencial.setBounds(50, 210, 230, 30);

        txtTelCel.setText("Telefone Celular");
        getContentPane().add(txtTelCel);
        txtTelCel.setBounds(290, 210, 230, 30);

        btCadastrar.setText("Cadastrar");
        getContentPane().add(btCadastrar);
        btCadastrar.setBounds(100, 260, 100, 30);

        btLimparDados.setText("Limpar Dados");
        getContentPane().add(btLimparDados);
        btLimparDados.setBounds(220, 260, 97, 30);

        btCancelar.setText("Cancelar");
        btCancelar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btCancelarActionPerformed(evt);
            }
        });
        getContentPane().add(btCancelar);
        btCancelar.setBounds(350, 260, 90, 30);

        getAccessibleContext().setAccessibleDescription("Cadastrar");

        setSize(new java.awt.Dimension(567, 381));
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void btCancelarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btCancelarActionPerformed
        dispose();
    }//GEN-LAST:event_btCancelarActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(TelaCadastro.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(TelaCadastro.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(TelaCadastro.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(TelaCadastro.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new TelaCadastro().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btCadastrar;
    private javax.swing.JButton btCancelar;
    private javax.swing.JButton btLimparDados;
    private javax.swing.JTextField txtCPF;
    private javax.swing.JTextField txtCidade;
    private javax.swing.JTextField txtComplemento;
    private javax.swing.JTextField txtEstado;
    private javax.swing.JTextField txtLogin;
    private javax.swing.JTextField txtNome;
    private javax.swing.JTextField txtNumero;
    private javax.swing.JTextField txtRua;
    private javax.swing.JPasswordField txtSenha;
    private javax.swing.JTextField txtTelCel;
    private javax.swing.JTextField txtTelResidencial;
    // End of variables declaration//GEN-END:variables
}
