/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package Views;

/**
 *
 * @author Pipitchu
 */
public class TelaPrincipalAdministrador extends javax.swing.JFrame {

    /**
     * Creates new form TelaPrincipal
     */
    public TelaPrincipalAdministrador() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        txtPesquisar = new javax.swing.JTextField();
        btBuscarMoveis = new javax.swing.JButton();
        btSalaDeEstar = new javax.swing.JButton();
        ImagemSala = new javax.swing.JLabel();
        Indisponivel = new javax.swing.JLabel();
        Indisponivel1 = new javax.swing.JLabel();
        btCozinha = new javax.swing.JButton();
        ImagemCozinha = new javax.swing.JLabel();
        btQuarto = new javax.swing.JButton();
        ImagemQuarto = new javax.swing.JLabel();
        Mobly = new javax.swing.JLabel();
        LinhaBackground = new javax.swing.JLabel();
        backgroundBlack = new javax.swing.JLabel();
        background = new javax.swing.JLabel();
        BarraDeMenu = new javax.swing.JMenuBar();
        MinhaConta = new javax.swing.JMenu();
        bMeusDados = new javax.swing.JMenuItem();
        bDadosClientes = new javax.swing.JMenuItem();
        bSairConta = new javax.swing.JMenuItem();
        Categorias = new javax.swing.JMenu();
        bSalaDeEstar = new javax.swing.JMenuItem();
        bCozinha = new javax.swing.JMenuItem();
        bQuarto = new javax.swing.JMenuItem();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("Mobly");
        setResizable(false);
        getContentPane().setLayout(null);

        txtPesquisar.setToolTipText("O que você está buscando ?");
        getContentPane().add(txtPesquisar);
        txtPesquisar.setBounds(30, 110, 290, 30);
        txtPesquisar.getAccessibleContext().setAccessibleName("O que você está buscando ?");

        btBuscarMoveis.setBackground(new java.awt.Color(255, 153, 0));
        btBuscarMoveis.setFont(new java.awt.Font("Arial", 1, 12)); // NOI18N
        btBuscarMoveis.setToolTipText("Buscar");
        getContentPane().add(btBuscarMoveis);
        btBuscarMoveis.setBounds(310, 110, 50, 30);
        btBuscarMoveis.getAccessibleContext().setAccessibleName("Buscar");

        btSalaDeEstar.setBackground(new java.awt.Color(255, 255, 255));
        btSalaDeEstar.setFont(new java.awt.Font("Arial", 1, 14)); // NOI18N
        btSalaDeEstar.setText("SALA DE ESTAR");
        btSalaDeEstar.setToolTipText("Sala de estar");
        btSalaDeEstar.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(204, 204, 204)));
        btSalaDeEstar.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        btSalaDeEstar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btSalaDeEstarActionPerformed(evt);
            }
        });
        getContentPane().add(btSalaDeEstar);
        btSalaDeEstar.setBounds(70, 540, 360, 40);

        ImagemSala.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagens/sala de estar.png"))); // NOI18N
        getContentPane().add(ImagemSala);
        ImagemSala.setBounds(70, 290, 360, 250);

        Indisponivel.setFont(new java.awt.Font("Arial", 1, 24)); // NOI18N
        Indisponivel.setForeground(new java.awt.Color(255, 0, 0));
        Indisponivel.setText("INDISPONIVEL");
        getContentPane().add(Indisponivel);
        Indisponivel.setBounds(910, 390, 180, 50);

        Indisponivel1.setFont(new java.awt.Font("Arial", 1, 24)); // NOI18N
        Indisponivel1.setForeground(new java.awt.Color(255, 0, 0));
        Indisponivel1.setText("INDISPONIVEL");
        getContentPane().add(Indisponivel1);
        Indisponivel1.setBounds(540, 390, 180, 50);

        btCozinha.setBackground(new java.awt.Color(255, 255, 255));
        btCozinha.setFont(new java.awt.Font("Arial", 1, 14)); // NOI18N
        btCozinha.setText("COZINHA");
        btCozinha.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        btCozinha.setEnabled(false);
        getContentPane().add(btCozinha);
        btCozinha.setBounds(440, 540, 360, 40);

        ImagemCozinha.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagens/Cozinha.png"))); // NOI18N
        ImagemCozinha.setEnabled(false);
        getContentPane().add(ImagemCozinha);
        ImagemCozinha.setBounds(440, 290, 360, 250);

        btQuarto.setBackground(new java.awt.Color(255, 255, 255));
        btQuarto.setFont(new java.awt.Font("Arial", 1, 14)); // NOI18N
        btQuarto.setText("QUARTO");
        btQuarto.setToolTipText("");
        btQuarto.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        btQuarto.setEnabled(false);
        getContentPane().add(btQuarto);
        btQuarto.setBounds(810, 540, 360, 40);

        ImagemQuarto.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagens/Quarto.png"))); // NOI18N
        ImagemQuarto.setEnabled(false);
        getContentPane().add(ImagemQuarto);
        ImagemQuarto.setBounds(810, 290, 360, 250);

        Mobly.setFont(new java.awt.Font("Arial", 1, 72)); // NOI18N
        Mobly.setForeground(new java.awt.Color(0, 0, 0));
        Mobly.setText("MOBLY");
        getContentPane().add(Mobly);
        Mobly.setBounds(470, 70, 280, 110);

        LinhaBackground.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagens/background white.jpg"))); // NOI18N
        LinhaBackground.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));
        getContentPane().add(LinhaBackground);
        LinhaBackground.setBounds(0, 70, 1280, 150);

        backgroundBlack.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagens/background white.jpg"))); // NOI18N
        getContentPane().add(backgroundBlack);
        backgroundBlack.setBounds(0, 260, 1280, 340);

        background.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagens/backgrpundazul.jpg"))); // NOI18N
        background.setToolTipText("");
        background.setVerticalAlignment(javax.swing.SwingConstants.TOP);
        getContentPane().add(background);
        background.setBounds(10, 0, 1280, 720);

        BarraDeMenu.setBackground(new java.awt.Color(255, 255, 255));

        MinhaConta.setText("Dados cadastrados");

        bMeusDados.setText("Meus Dados");
        MinhaConta.add(bMeusDados);

        bDadosClientes.setText("Dados Clientes");
        MinhaConta.add(bDadosClientes);

        bSairConta.setText("Sair da conta");
        bSairConta.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                bSairContaActionPerformed(evt);
            }
        });
        MinhaConta.add(bSairConta);

        BarraDeMenu.add(MinhaConta);

        Categorias.setText("Categorias");

        bSalaDeEstar.setText("Sala de Estar");
        bSalaDeEstar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                bSalaDeEstarActionPerformed(evt);
            }
        });
        Categorias.add(bSalaDeEstar);

        bCozinha.setForeground(new java.awt.Color(255, 0, 0));
        bCozinha.setText("Cozinha");
        Categorias.add(bCozinha);

        bQuarto.setForeground(new java.awt.Color(255, 0, 0));
        bQuarto.setText("Quarto");
        Categorias.add(bQuarto);

        BarraDeMenu.add(Categorias);

        setJMenuBar(BarraDeMenu);

        getAccessibleContext().setAccessibleDescription("Mobly");

        setSize(new java.awt.Dimension(1266, 739));
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void bSairContaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_bSairContaActionPerformed
        TelaLogin login = new TelaLogin();
        dispose();
        login.setVisible(true);
    }//GEN-LAST:event_bSairContaActionPerformed

    private void btSalaDeEstarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btSalaDeEstarActionPerformed
        TelaSalaDeEstar sala = new TelaSalaDeEstar();
        sala.setVisible(true);
    }//GEN-LAST:event_btSalaDeEstarActionPerformed

    private void bSalaDeEstarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_bSalaDeEstarActionPerformed
        TelaSalaDeEstarAdministrador sala = new TelaSalaDeEstarAdministrador();
        sala.setVisible(true);
    }//GEN-LAST:event_bSalaDeEstarActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(TelaPrincipalAdministrador.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(TelaPrincipalAdministrador.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(TelaPrincipalAdministrador.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(TelaPrincipalAdministrador.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new TelaPrincipalAdministrador().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JMenuBar BarraDeMenu;
    private javax.swing.JMenu Categorias;
    private javax.swing.JLabel ImagemCozinha;
    private javax.swing.JLabel ImagemQuarto;
    private javax.swing.JLabel ImagemSala;
    private javax.swing.JLabel Indisponivel;
    private javax.swing.JLabel Indisponivel1;
    private javax.swing.JLabel LinhaBackground;
    private javax.swing.JMenu MinhaConta;
    private javax.swing.JLabel Mobly;
    private javax.swing.JMenuItem bCozinha;
    private javax.swing.JMenuItem bDadosClientes;
    private javax.swing.JMenuItem bMeusDados;
    private javax.swing.JMenuItem bQuarto;
    private javax.swing.JMenuItem bSairConta;
    private javax.swing.JMenuItem bSalaDeEstar;
    private javax.swing.JLabel background;
    private javax.swing.JLabel backgroundBlack;
    private javax.swing.JButton btBuscarMoveis;
    private javax.swing.JButton btCozinha;
    private javax.swing.JButton btQuarto;
    private javax.swing.JButton btSalaDeEstar;
    private javax.swing.JTextField txtPesquisar;
    // End of variables declaration//GEN-END:variables
}
